export type DailyType = {
    Area?:                          string;
    Branch?:                        string;
    ByUser?:                        string;
    Date:                           string;
    SourceType:                     string;
    sourceName:                     string;
    ProductionVolume:               number;
    OperationHours:                 number;
    ServiceInterruption:            number;
    TotalHoursServiceInterruption:  number;
    ElectricityConsumption:         number;
    VFDfrequency:                   number;
    SpotFlow:                       number;
    SpotPressure:                   number;
    TimeSpotMeasurements:           number;
    LineVoltage1:                   number;
    LineVoltage2:                   number;
    LineVoltage3:                   number;
    LineCurrent1:                   number;
    LineCurrent2:                   number;
    LineCurrent3:                   number;
    Status:                         string;
    Comment:                        string;
};

export type MonthlyType = {
    Area?:                          string;
    Branch?:                        string;
    ByUser:                         string;
    Month:                          string;
    Year:                           number;
    SourceType:                     string;
    sourceName:                     string;
    ElectricityConsumption:         number;
    ElectricityCost:                number;
    BulkCost:                       number;
    BulkOuttake:                    string;
    BulkProvider:                   string;
    WTPcost:                        number;
    WTPsource:                      number;
    WTPvolume:                      number;
    DisinfectionMode:               string;
    DisinfectantCost:               number;
    DisinfectionAmount:             number;
    DisinfectionBrandType:          string;
    OtherTreatmentCost:             number;
    EmergencyFuelCost:              number;
    EmergencyTotalHoursUsed:        number;
    GensetFuelCost:                 number;
    Status:                         string;
    Remarks:                        string;
};